Fun value (fixes #7)
crumblingstatue/FloweysTimeMachine pull request #48
Opened 2017-03-24 08:37 UTC by LEGOlord208

2017-03-24 15:07 UTC, LEGOlord208 commented
bump?  
(He accepted all my other pulls)

2017-03-24 15:18 UTC, crumblingstatue requested changes

2017-03-24 15:18 UTC, crumblingstatue commented on main.js
> +    if(fun){
Small nitpick, but can you keep the formatting consitent? ( `if (fun) {` )

2017-03-24 21:27 UTC, LEGOlord208 commented on main.js
> +    if(fun){
Sorry, yes! Will do tomorrow. If you don't feel like changing it. I left the "allow edits from maintainers" checkbox on

2017-03-25 05:23 UTC, LEGOlord208 commented
Fixed!

2017-03-25 07:04 UTC, crumblingstatue approved these changes

2017-03-25 07:05 UTC, merged